name: AI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - matplotlib=3.9.1
  - seaborn=0.13.2
  - tqdm=4.66.5
  - flask=3.0.3
  - mlflow=2.15.1
  - tensorflow=2.8.1
  - tensorflow-hub=0.16.1
  - torch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - cudatoolkit=11.8  # Si vous utilisez un GPU
  - xgboost=2.1.1
  - lightgbm=4.5.0
  - spacy=3.7.5
  - nltk=3.8.1
  - h5py=3.11.0
  - pillow=10.2.0
  - jupyterlab=4.2.4
  - ipywidgets=8.1.3
  - pip:
      - dask==2024.8.0
      - gensim==4.3.3
      - keras==3.5.0
      - triton==3.0.0
      - tqdm-joblib==0.0.4
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - transformers==4.33.3
      - widgetsnbextension==4.0.11

